### ISSUE TITLE
ImportError: no module named '_version' in Python 3.3

### ISSUE THREAD

**Issue by yong27** [dyve/django-bootstrap-toolkit#71]
I do not know why ImportError is occurred in Python 3.3

**Comment by ckommula** [comment]
When I try with SOAPpy, I am facing the same kind of issue, so I navigated to the location of "C:\Users\123\AppData\Local\Programs\Python\Python36-32\lib\site-packages\SOAPpy\__init__.py" and edited like below but still facing the issue like:

Modified : from ._version import __version__

Error: ModuleNotFoundError: No module named 'SOAPpy._version'
